<div class="content wrapper cf">
  <div class="static_content static_page">
    <h2>Internal Error</h2>
    <div>
      We have encountered an error in the system. Our engineers have been notified
      to fix the issue. Please check back soon.
    </div>
    <% if !@exception.nil? %>
      <h3>Technical Information for Developers</h3>
      <div>Visible since you're coming from <%= request.ip %>, an internal IP.</div>
      <h3><%= @exception.message %></h3>
      <div class="exception-message"><% @exception.backtrace.each do |i| %>
    <%= i %>
<% end %></div>
    <% end %>
  </div>
</div>
